# Generated by Django 3.1.7 on 2021-02-25 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Insta',
            new_name='Insta_rating',
        ),
    ]
